"""Assemble final report Markdown."""

from __future__ import annotations

from collections import Counter
from datetime import date

from .models import Message
from .sanitizer import SanitizeStats


def build_prompt(messages: list[Message], on: date) -> str:
    """Compose the LLM input from sanitized messages."""

    lines = [f"# 当日 ({on.isoformat()}) AI 会话原文", ""]
    for m in messages:
        head = f"[{m.timestamp.astimezone().strftime('%H:%M')}] [{m.source}/{m.role}]"
        if m.cwd:
            head += f" cwd={m.cwd}"
        lines.append(head)
        lines.append(m.content)
        lines.append("")
    return "\n".join(lines)


def build_stats(messages: list[Message], stats: SanitizeStats) -> str:
    """Render the stats footer."""

    by_source = Counter(m.source for m in messages)
    by_role = Counter(m.role for m in messages)
    cwds = Counter(m.cwd for m in messages if m.cwd)

    lines = ["## 📊 原始统计", ""]
    lines.append("**会话条数**")
    for src, n in by_source.most_common():
        lines.append(f"- {src}: {n}")
    lines.append("")
    lines.append("**角色分布**")
    for role, n in by_role.most_common():
        lines.append(f"- {role}: {n}")
    if cwds:
        lines.append("")
        lines.append("**涉及目录 (Top 5)**")
        for cwd, n in cwds.most_common(5):
            lines.append(f"- `{cwd}`: {n}")
    if stats.redactions or stats.long_code_trimmed or stats.env_blocks_removed:
        lines.append("")
        lines.append("**脱敏统计**")
        for k, v in stats.redactions.items():
            lines.append(f"- {k}: {v}")
        if stats.long_code_trimmed:
            lines.append(f"- long_code_trimmed: {stats.long_code_trimmed}")
        if stats.env_blocks_removed:
            lines.append(f"- env_blocks_removed: {stats.env_blocks_removed}")
    lines.append("")
    return "\n".join(lines)


def build_report(
    on: date,
    summary_md: str,
    stats_md: str,
    diff_md: str,
    backend: str,
) -> str:
    """Final document layout."""

    header = (
        f"# {on.isoformat()} 开发日报\n\n"
        f"> backend: `{backend}`  ·  generated by devlog\n\n"
    )
    parts = [header, summary_md.strip(), ""]
    if diff_md:
        parts.extend([diff_md.strip(), ""])
    parts.extend([stats_md.strip(), ""])
    return "\n".join(parts)
